server:
  port: ${PORT:8300}
spring:
  application:
    name: user-api
eureka:
  client:
    service-url:
      #if no EUREKA_URL is set, default to http://localhost:8761/eureka
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
